name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Publish ni-fpga-sys
      working-directory: ./ni-fpga-sys
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_ACCESS_TOKEN }}
      run: git diff --quiet HEAD^ ./Cargo.toml || (cargo publish +nightly && sleep 15)
    - name: Publish ni-fpga
      working-directory: ./ni-fpga
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_ACCESS_TOKEN }}
      run: git diff --quiet HEAD^ ./Cargo.toml || cargo publish +nightly
    - name: Publish ni-fpga-macros
      working-directory: ./ni-fpga-macros
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_ACCESS_TOKEN }}
      run: git diff --quiet HEAD^ ./Cargo.toml || cargo publish +nightly
